# Generated by Django 4.2.30 on 2026-05-26 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('installation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('system_capacity_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('install_date', models.DateField()),
                ('status', models.CharField(default='operational', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('reading_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('output_kw', models.DecimalField(decimal_places=3, max_digits=10)),
                ('battery_voltage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=6)),
                ('irradiance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alert_flags', models.JSONField(blank=True, default=dict)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='models.installation')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('technician_id', models.CharField(blank=True, max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, max_length=20, null=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='models.installation')),
            ],
        ),
    ]
