# Generated by Django 4.2.30 on 2026-05-26 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportShipment',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_ids', models.JSONField(default=list)),
                ('buyer_id', models.CharField(max_length=50)),
                ('destination_country', models.CharField(max_length=5)),
                ('departure_date', models.DateField()),
                ('certificate_ids', models.JSONField(blank=True, default=list)),
                ('customs_status', models.CharField(default='pending', max_length=20)),
                ('hold_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_id', models.CharField(max_length=50)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('certification_status', models.CharField(default='organic', max_length=50)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('additional_certs', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_method', models.CharField(max_length=20)),
                ('quality_grade', models.CharField(max_length=5)),
                ('intake_agent_id', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_batches', to='models.farm')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField()),
                ('operator_id', models.CharField(max_length=50)),
                ('output_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='models.harvestbatch')),
            ],
        ),
    ]
