version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: fintech/Dockerfile
    network_mode: host
    env_file: ../.env
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
    depends_on:
      - db
    restart: on-failure

  db:
    build:
      context: ..
      dockerfile: fintech/Dockerfile.db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sita}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sita_pass}
      POSTGRES_DB: ${POSTGRES_DB:-sita_sprint}
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
    restart: on-failure

volumes:
  pgdata:
