# Generated by Django 4.2.30 on 2026-05-26 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('encounter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.CharField(max_length=50)),
                ('clinician_id', models.CharField(max_length=50)),
                ('encounter_date', models.DateTimeField()),
                ('encounter_type', models.CharField(max_length=30)),
                ('diagnosis_codes', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('registered_facility_id', models.CharField(max_length=50)),
                ('golden_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mdm_confidence', models.FloatField(blank=True, null=True)),
                ('mdm_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_facility_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='models.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=100)),
                ('result_value', models.CharField(max_length=100)),
                ('normal_range', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField()),
                ('source_lab', models.CharField(max_length=100)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='models.encounter')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='models.patient'),
        ),
    ]
